sudo: required
dist: trusty
language: node_js
node_js:
  - '6'

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

cache:
  bundler: true
  directories:
  - node_modules
  - $(npm config get prefix)

addons:

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install gulp -g
  - npm install bower -g

script:
  - bower install
  - gulp travis:build

after_success:
  - npm install codeclimate-test-reporter -g
  - codeclimate-test-reporter < reports/lcov/lcov.info
  - test $TRAVIS_BRANCH = "master"

after_success:
- bash gh_pages.sh
